import React,{useState}from'react';import{createRoot}from'react-dom/client';import{BrowserRouter,Routes,Route,Link,Navigate,useNavigate}from'react-router-dom';import'./styles.css';
const clubs=[{id:1,name:'Technology Club',category:'Academic',description:'Software, hardware, and technology projects.',meeting:'Tuesday 5:00 PM',status:'Active'},{id:2,name:'Business Club',category:'Academic',description:'Networking and entrepreneurship activities.',meeting:'Wednesday 4:00 PM',status:'Active'},{id:3,name:'Photography Club',category:'Creative',description:'Photo walks and editing workshops.',meeting:'Friday 3:00 PM',status:'Active'}];
const seedEvents=[{id:1,clubId:1,title:'Web Development Workshop',date:'2026-07-24',time:'2:00 PM',location:'Progress Campus A201',description:'Beginner web workshop.'},{id:2,clubId:2,title:'Startup Pitch Practice',date:'2026-07-26',time:'4:00 PM',location:'Progress Campus B105',description:'Practice a business pitch.'}];
const seedRequests=[{id:1,student:'Sarah Johnson',club:'Technology Club',status:'Pending'},{id:2,student:'Daniel Lee',club:'Business Club',status:'Pending'}];
const seedUsers=[{id:1,name:'Sarah Johnson',email:'sarah@college.ca',role:'Student'},{id:2,name:'Daniel Lee',email:'daniel@college.ca',role:'Club Executive'},{id:3,name:'Michael Brown',email:'michael@college.ca',role:'Administrator'}];
const get=(k,d)=>JSON.parse(localStorage.getItem(k)||JSON.stringify(d));const set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function App(){const[user,setUser]=useState(get('currentUser',null));const login=r=>{const u={name:r==='Student'?'Sarah':r==='Club Executive'?'Daniel':'Michael',role:r};set('currentUser',u);setUser(u)};const logout=()=>{localStorage.removeItem('currentUser');setUser(null)};return <Routes><Route path="/" element={<Login user={user} login={login}/>}/><Route path="/unauthorized" element={<Unauthorized/>}/><Route path="/student/*" element={<Guard user={user} role="Student"><Student user={user} logout={logout}/></Guard>}/><Route path="/executive/*" element={<Guard user={user} role="Club Executive"><Executive user={user} logout={logout}/></Guard>}/><Route path="/admin/*" element={<Guard user={user} role="Administrator"><Admin user={user} logout={logout}/></Guard>}/><Route path="*" element={<Navigate to="/"/>}/></Routes>}
function Guard({user,role,children}){if(!user)return <Navigate to="/"/>;if(user.role!==role)return <Navigate to="/unauthorized"/>;return children}
function Login({user,login}){const n=useNavigate();if(user)return <Navigate to={user.role==='Student'?'/student/clubs':user.role==='Club Executive'?'/executive/requests':'/admin/dashboard'}/>;const go=r=>{login(r);n(r==='Student'?'/student/clubs':r==='Club Executive'?'/executive/requests':'/admin/dashboard')};return <main className="center"><section className="login"><h1>Campus Club Management System</h1><p>Select a test role</p><button onClick={()=>go('Student')}>Login as Student</button><button onClick={()=>go('Club Executive')}>Login as Club Executive</button><button onClick={()=>go('Administrator')}>Login as Administrator</button></section></main>}
const Unauthorized=()=> <main className="center"><section className="card"><h1>Unauthorized Access</h1><p>You do not have permission to view this page.</p><Link to="/">Return to Login</Link></section></main>;
function Layout({title,user,logout,links,children}){return <><header><div><h2>{title}</h2><span>{user.name} — {user.role}</span></div><button className="secondary" onClick={logout}>Logout</button></header><nav>{links.map(x=><Link key={x.to} to={x.to}>{x.label}</Link>)}</nav><main className="container">{children}</main></>}
function Student({user,logout}){return <Layout title="Student Portal" user={user} logout={logout} links={[{to:'/student/clubs',label:'Search Clubs'},{to:'/student/events',label:'Browse Events'}]}><Routes><Route path="clubs" element={<SearchClubs/>}/><Route path="clubs/:id" element={<ClubDetails/>}/><Route path="events" element={<BrowseEvents/>}/><Route path="events/:id/register" element={<Register/>}/></Routes></Layout>}
function SearchClubs(){const[q,setQ]=useState('');const list=clubs.filter(c=>(c.name+c.description).toLowerCase().includes(q.toLowerCase()));return <section><h1>Search Clubs</h1><input placeholder="Enter club name or keyword" value={q} onChange={e=>setQ(e.target.value)}/><div className="grid">{list.map(c=><article className="card" key={c.id}><h3>{c.name}</h3><p>{c.category}</p><p>{c.description}</p><Link className="linkbtn" to={`/student/clubs/${c.id}`}>Select Club</Link></article>)}</div>{!list.length&&<p>No clubs found.</p>}</section>}
function ClubDetails(){const id=Number(location.pathname.split('/').pop()),c=clubs.find(x=>x.id===id);return c?<section className="card"><h1>{c.name}</h1><p><b>Category:</b> {c.category}</p><p><b>Description:</b> {c.description}</p><p><b>Meeting:</b> {c.meeting}</p><p>Selected club: {c.name}</p></section>:<p>Club not found.</p>}
function BrowseEvents(){const list=get('events',seedEvents);return <section><h1>Browse Events</h1><div className="grid">{list.map(e=><article className="card" key={e.id}><h3>{e.title}</h3><p>{clubs.find(c=>c.id===e.clubId)?.name}</p><p>{e.date} at {e.time}</p><p>{e.location}</p><Link className="linkbtn" to={`/student/events/${e.id}/register`}>Register</Link></article>)}</div></section>}
function Register(){const id=Number(location.pathname.split('/')[3]),e=get('events',seedEvents).find(x=>x.id===id),[m,setM]=useState('');const submit=()=>{const r=get('registrations',[]);if(r.some(x=>x.eventId===id)){setM('You are already registered for this event.');return}set('registrations',[...r,{id:Date.now(),eventId:id,student:'Sarah Johnson'}]);setM('Registration submitted successfully.')};return e?<section className="card"><h1>Submit Event Registration</h1><h3>{e.title}</h3><p>{e.date} at {e.time}</p><p>{e.location}</p><button onClick={submit}>Submit Registration</button>{m&&<p className="message">{m}</p>}</section>:<p>Event not found.</p>}
function Executive({user,logout}){return <Layout title="Club Executive Portal" user={user} logout={logout} links={[{to:'/executive/requests',label:'Join Requests'},{to:'/executive/events/create',label:'Create Event'},{to:'/executive/events',label:'Edit Events'},{to:'/executive/announcements/create',label:'Create Announcement'}]}><Routes><Route path="requests" element={<Requests/>}/><Route path="events/create" element={<CreateEvent/>}/><Route path="events" element={<EventList/>}/><Route path="events/:id/edit" element={<EditEvent/>}/><Route path="announcements/create" element={<Announcement/>}/></Routes></Layout>}
function Requests(){const[items,setItems]=useState(get('requests',seedRequests));const update=(id,status)=>{const n=items.map(x=>x.id===id?{...x,status}:x);setItems(n);set('requests',n)};return <section><h1>Review Join Requests</h1>{items.map(x=><article className="card row" key={x.id}><div><h3>{x.student}</h3><p>{x.club}</p><p>Status: {x.status}</p></div>{x.status==='Pending'&&<div><button onClick={()=>update(x.id,'Approved')}>Approve</button><button className="danger" onClick={()=>update(x.id,'Rejected')}>Reject</button></div>}</article>)}</section>}
function CreateEvent(){const[f,setF]=useState({title:'',date:'',time:'',location:'',description:''}),[m,setM]=useState('');const save=e=>{e.preventDefault();if(!f.title||!f.date||!f.time||!f.location){setM('Complete all required fields.');return}set('events',[...get('events',seedEvents),{id:Date.now(),clubId:1,...f}]);setF({title:'',date:'',time:'',location:'',description:''});setM('Event created successfully.')};return <EventForm title="Create Event" f={f} setF={setF} save={save} m={m}/>}
function EventList(){return <section><h1>Edit Events</h1>{get('events',seedEvents).map(e=><article className="card" key={e.id}><h3>{e.title}</h3><p>{e.date} at {e.time}</p><Link className="linkbtn" to={`/executive/events/${e.id}/edit`}>Edit Event</Link></article>)}</section>}
function EditEvent(){const id=Number(location.pathname.split('/')[3]),events=get('events',seedEvents),old=events.find(x=>x.id===id),[f,setF]=useState(old||{}),[m,setM]=useState('');const save=e=>{e.preventDefault();set('events',events.map(x=>x.id===id?{...x,...f}:x));setM('Event updated successfully.')};return old?<EventForm title="Edit Event" f={f} setF={setF} save={save} m={m}/>:<p>Event not found.</p>}
function EventForm({title,f,setF,save,m}){return <form className="card form" onSubmit={save}><h1>{title}</h1>{['title','date','time','location','description'].map(k=><label key={k}>{k[0].toUpperCase()+k.slice(1)}{k==='description'?<textarea value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}/>:<input type={k==='date'?'date':'text'} value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}/>}</label>)}<button>Save</button>{m&&<p className="message">{m}</p>}</form>}
function Announcement(){const[f,setF]=useState({title:'',content:''}),[m,setM]=useState('');const save=e=>{e.preventDefault();if(!f.title||!f.content){setM('Title and content are required.');return}set('announcements',[...get('announcements',[]),{id:Date.now(),...f,status:'Draft'}]);setF({title:'',content:''});setM('Announcement created successfully.')};return <form className="card form" onSubmit={save}><h1>Create Announcement</h1><label>Title<input value={f.title} onChange={e=>setF({...f,title:e.target.value})}/></label><label>Content<textarea value={f.content} onChange={e=>setF({...f,content:e.target.value})}/></label><button>Save Announcement</button>{m&&<p className="message">{m}</p>}</form>}
function Admin({user,logout}){return <Layout title="Administrator Portal" user={user} logout={logout} links={[{to:'/admin/dashboard',label:'Dashboard'},{to:'/admin/users',label:'Update User Role'},{to:'/admin/clubs',label:'View Clubs'}]}><Routes><Route path="dashboard" element={<Dashboard/>}/><Route path="users" element={<Users/>}/><Route path="clubs" element={<AdminClubs/>}/></Routes></Layout>}
function Dashboard(){return <section><h1>Administrator Dashboard</h1><div className="stats"><article className="card"><h2>{get('users',seedUsers).length}</h2><p>Users</p></article><article className="card"><h2>{clubs.length}</h2><p>Clubs</p></article><article className="card"><h2>{get('events',seedEvents).length}</h2><p>Events</p></article><article className="card"><h2>{get('registrations',[]).length}</h2><p>Registrations</p></article></div></section>}
function Users(){const[u,setU]=useState(get('users',seedUsers)),[m,setM]=useState('');const update=(id,role)=>{const n=u.map(x=>x.id===id?{...x,role}:x);setU(n);set('users',n);setM('User role updated successfully.')};return <section><h1>Update User Role</h1>{u.map(x=><article className="card row" key={x.id}><div><h3>{x.name}</h3><p>{x.email}</p></div><select value={x.role} onChange={e=>update(x.id,e.target.value)}><option>Student</option><option>Club Executive</option><option>Administrator</option></select></article>)}{m&&<p className="message">{m}</p>}</section>}
function AdminClubs(){return <section><h1>View Clubs</h1><table><thead><tr><th>Name</th><th>Category</th><th>Meeting</th><th>Status</th></tr></thead><tbody>{clubs.map(c=><tr key={c.id}><td>{c.name}</td><td>{c.category}</td><td>{c.meeting}</td><td>{c.status}</td></tr>)}</tbody></table></section>}
createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
